SWM-team-forever/dadamda-frontend

- src/App.js
> [DAD-327] feat: 프론트엔드 배포 확인

- src/App.tsx
- src/components/molcules/Header.tsx
- src/components/molcules/MobileNavbar.tsx
- src/components/organisms/LoginModal.tsx
- src/context/UserContext.tsx
DAD-433
- user context를 전역 context로 뺌
- 가짜 로그인 기능을 활성화 하면 가짜 유저 이미지 확인 가능 및 몇 메뉴 오픈
가짜 로그인 기능을 진짜 로그인 기능으로 변경
> [DAD-433] feat: 가짜 로그인 기능 구현

- src/App.tsx
- src/components/atoms/DefaultButton.tsx
- src/components/atoms/ProfileImage.tsx
- src/components/molcules/Header.tsx
- src/components/molcules/MobileNavbar.tsx
- src/components/organisms/LoginModal.tsx
- src/components/scrap/ArticleTemplate.tsx
- src/components/scrap/ProductTemplate.tsx
- src/components/scrap/Sidebar.tsx
- src/context/UserContext.tsx
- src/pages/AuthPage.tsx
- src/pages/MainPage.tsx
- src/pages/ScrapPage.tsx
- src/pages/UserPage.tsx
- src/stories/Button.stories.ts
- src/stories/Button.tsx
- src/stories/Header.tsx
DAD-459
- 타입 스크립트 에러 수정 -> 빌드 가능
- `85572bc` UserConsumer 함수에서 ts 에러가 발생 -> 해결하지 못해서 관련 타입을 모두 any로 변경 
```
당시 에러 : Type 'object | null' must have a '[Symbol.iterator]()' method that returns an iterator.ts(2488)
```
> [DAD-459] 타입스크립트 에러 잡기

- src/components/atoms/ProfileImage.tsx
- src/components/atoms/Tooltip.tsx
- src/components/molcules/Header.tsx
- src/stories/Tooltip.stories.ts
DAD-460
유저 로그인 툴팁 추가
- hover시 font 색상 primary color로 지정
- 각 클릭 시 유저 페이지 / 메인 페이지로 이동
- 로그아웃 기능 연결
- tooltip 스토리북 작업
- tooltip 일반화된 채로 작업할 수 있게 변경(부모로부터의 위치)
- 프로필 수정 -> 프로필 정보 문구 수정?
> [DAD-460] 유저 로그인 tooltip 추가

- package-lock.json
- package.json
- src/components/atoms/ColumnContainer.tsx
- src/components/atoms/RowContainer.tsx
- src/components/organisms/LoginModal.tsx
- tsconfig.json
DAD-484
- ts 에러 수정 - tsconfig 설정 변경
- process is not defined 에러 해결 (override 설정 추가, react-scripts 추가)
> [DAD-484] 에러 수정

- .gitignore
- package-lock.json
- package.json
- src/components/atoms/DefaultButton.tsx
- src/components/atoms/Tooltip.tsx
- src/components/molcules/Header.tsx
- src/components/molcules/Navbar.tsx
- src/components/molcules/OtherScrapCard.tsx
- src/components/organisms/LoginModal.tsx
- src/components/organisms/ScrapCreateModal.tsx
- src/components/scrap/Sidebar.tsx
DAD-487
ts 오류 수정(type 잘못 지정)
typescript option styled component 설치
> [DAD-487] ts 추가 오류 수정

- index.html
- src/App.tsx
- src/components/atoms/Chip.tsx
- src/components/atoms/ColumnContainer.tsx
- src/components/atoms/RowContainer.tsx
- src/components/atoms/TextArea.tsx
- src/components/molcules/ArticleScrapCard.tsx
- src/components/molcules/MemoTextArea.tsx
- src/components/molcules/OtherScrapCard.tsx
- src/components/molcules/ProductScrapCard.tsx
- src/components/molcules/ScrapListHeader.tsx
- src/components/molcules/VideoScrapCard.tsx
- src/components/organisms/EmptyScrapContainer.tsx
- src/components/organisms/ExistListScrapContainer.tsx
- src/components/organisms/MemoCreateModal.tsx
- src/components/organisms/ScrapCreateModal.tsx
- src/components/organisms/ScrapDeleteModal.tsx
- src/components/organisms/ScrapEditModal.tsx
- src/components/templates/ListTemplate.tsx
- src/components/templates/OtherTemplate.tsx
- src/components/templates/ScrapTemplate.tsx
- src/stories/ProductScrapCard.stories.ts
- src/stories/ScrapEditModal.stories.ts
- src/stories/VideoScrapCard.stories.ts
DAD-494
- 상품 스크랩, 비디오 스크랩 UI 작성
- 각 스크랩 템플릿 컴포넌트로 분리
- 스크랩 수정하기 기능 구현
- 수정하기 내 메모 파트 컴포넌트 분리
[블로그 이미지 볼 수 없던 오류 해결 참고](https://americanopeople.tistory.com/358)
> [DAD-494] 스크랩 수정하기 기능 구현 및 오류 수정

- src/components/atoms/TextArea.tsx
- src/components/molcules/MemoTextArea.tsx
- src/components/organisms/MemoCreateModal.tsx
- src/components/organisms/ScrapCreateModal.tsx
- src/components/organisms/ScrapDeleteModal.tsx
- src/components/organisms/ScrapEditModal.tsx
- src/components/templates/ScrapTemplate.tsx
DAD-534
- 스크랩 편집 후 내용 기존 내용에 덮어쓰기
- API와 연결
- 작업 도중 생긴 문제점 해결
1. 기존 배열 새로운 배열로 덮어쓸 때 특정 key 접근 불가 문제
- 해결 :  (key를 대괄호로 감쌌더니 해결됨)
2. hidestate를 undefined로 설정해둠 → api에서 필요로 하는 타입은 null
- 해결 : hidestate를 setstate로 통일하고, 각 state가 가질 수 있는 타입에 null 추가
3. edittext에서 다 지우면 해당 필드가 사라지고 값으로는 빈 문자열이 들어옴
- 해결 : element의 state가 존재할 때만 그리던 조건을 null이 아닐 때 그리고 null일 때 안 그리는 조건으로 변경
4. 가격 같은 필드는 자동으로 형식을 맞춰줘야 하는 것 아닌가 → MVP 이후 반영 예정
> [DAD-534] 수정하기 API 연결

- src/components/atoms/TextArea.tsx
- src/components/molcules/ArticleScrapCard.tsx
- src/components/molcules/OtherScrapCard.tsx
- src/components/molcules/ProductScrapCard.tsx
- src/components/molcules/VideoScrapCard.tsx
- src/components/organisms/ScrapEditModal.tsx
DAD-539
- 각 스크랩 요소 삭제마다 정렬 및 배치 요소 변경
- 삭제 불가능 요소 고려
- textarea가 비었을 때 빈 문자열을 넘기고 있음 -> null로 바꾸기 실패
- 어차피 추후 유효성 검사 구현해야 하니 만약 빈 문자열인 상태로 수정하기 / 추가하기 버튼 누르면 단계가 넘어가지 않도록 구현하는 게 나을 듯
> [DAD-539] 삭제 가능 여부 구현

- src/components/molcules/VideoScrapCard.tsx
- src/components/organisms/ExistListScrapContainer.tsx
- src/components/organisms/ExistOtherScrapContainer.tsx
- src/components/templates/ListTemplate.tsx
- src/components/templates/OtherTemplate.tsx
- src/components/templates/ScrapTemplate.tsx
- src/hooks/useInfiniteScroll.ts
- src/stories/ScrapEditModal.stories.ts
- src/stories/VideoScrapCard.stories.ts
DAD-533
- 무한 스크롤 구현
- 스크롤 하단 더 이상 목록이 없다는 문구 추가
- 스크랩 개수 알려주는 API 연결
> [DAD-533] 무한 스크롤 구현

- src/components/atoms/LoginButton.tsx
- src/components/molcules/Header.tsx
- src/components/molcules/MobileNavbar.tsx
- src/components/organisms/UserDeleteModal.tsx
- src/pages/GoogleOAuthLoginPage.tsx
- src/pages/UserPage.tsx
DAD-536 : 탈퇴하기 기능
DAD-551 : 로그아웃 기능
DAD-552 : 프로필 이미지 header에 적용
DAD-553 : 회원 정보 조회
DAD-554 : 모바일 navbar 라우팅 연결
탈퇴하기 API와 연결
로그아웃 기능구현
프로필 이미지 API요청 후 localstorage에 저장 및 header에 적용
회원 정보 조회 API 연결
모바일 navbar 라우팅 추가
> [DAD-532] 유저 페이지 추가 작업

- src/components/templates/ListTemplate.tsx
- src/stories/VideoScrapCard.stories.ts
> [DAD-622] fix: 타입스크립트 에러 수정

- .github/workflows/main.yml
- DAD-621
- cloudfront 캐시 삭제를 위한 GitHub Actions yml 변경
> [DAD-621] feat: cloudfront 캐시 삭제를 위한 GitHub Actions yml 변경

- src/App.tsx
- src/components/molcules/ArticleScrapCard.tsx
- src/components/molcules/Memo.tsx
- src/components/molcules/MemoTextArea.tsx
- src/components/organisms/ScrapEditModal.tsx
- src/components/templates/ScrapTemplate.tsx
- src/pages/MainPage.tsx
- src/utility/ErrorHandler.tsx
- DAD-624 : 채널톡 페이지 위치 고정
- DAD-625 : published date 카드 수정하기 모달 오류 수정
- DAD-626 : 이미지 메모 편집하기 오류 해결
- DAD-628 : 장소 페이지 오류
- 채널톡 페이지 위치 고정을 위해 main page에 useEffect의 cleanup 함수로 사라지도록 설정
- 수정하기 모달 오류는 수정할 필요가 없는 요소를 순회 대상에서 제거하여 해결
- 이미지 메모는 변수를 잘못 연결해둔 문제 해결
- 편집하기 모달 내에서 메모 추가할 때 edittext에 이미 텍스트가 입력되어있는 문제는 해당 텍스트를 빈 문자열로 바꾸어 해결
- 장소 페이지 오류를 해결하기 위해선 준비되지 않은 페이지들에서 서버에 요청을 날리지 않도록 설정하면 되지만, 현재 정의하지 않은 오류들이 많이 발생하고 있기 때문에 정의되지 않은 오류를 자동으로 처리하는 로직이 완성된 이후 해결하는 것이 나을 것으로 판단함.
> [DAD-623] [버그] 프론트엔드 버그 수정

- .github/workflows/main.yml
- DAD-647
- op.push.branches를 develop으로 변경
- 러너 운영체제 버전 명시
> [DAD-647] refactor: op.push.branches를 develop으로 변경 및 러너 운영체제 버전 명시

- README.md
- src/components/atoms/CategoryItem/AuthorElement.tsx
- src/components/atoms/CategoryItem/AuthorImageElement.tsx
- src/components/atoms/CategoryItem/BlogNameElement.tsx
- src/components/atoms/CategoryItem/DescrptionElement.tsx
- src/components/atoms/CategoryItem/IconButtonListElement.tsx
- src/components/atoms/CategoryItem/PublishedDateElement.tsx
- src/components/atoms/CategoryItem/SiteNameElement.tsx
- src/components/atoms/CategoryItem/TitleElement.tsx
- src/components/atoms/Overlay.tsx
- src/components/atoms/Tooltip.tsx
- src/components/molcules/CategoryItem/DesktopArticleListElement.tsx
- src/components/molcules/CategoryItem/MobileArticleListElement.tsx
- src/components/organisms/ExistArticleScrapContainer.tsx
- src/components/organisms/ExistProductScrapContainer.tsx
- src/components/templates/ArticleTemplate.tsx
- src/components/templates/ScrapTemplate.tsx
- src/context/CategoryItemContext.tsx
- src/context/CategoryListContext.tsx
- DAD-656 : 아티클 페이지 작업
- DAD-689 : 리드미 파일 업데이트
- 데스크탑, 모바일 아티클 페이지 생성
- 데스크탑 페이지에서 iframe을 삽입하여 화면 비율 조정
- 스크롤 영역이 과도하게 많음 -> 스크롤 안 보이는데 스크롤이 되게 or 스크롤 커스터마이징 기능 도입
- 무한 스크롤 기능 적용
> [DAD-656] 아티클 페이지 작업

- .github/workflows/release.yml
- DAD-691
- 프론트엔드 Release GHA 파일 추가
> [DAD-691] 프론트엔드 Release GHA 파일 추가

- public/robots.txt
- DAD-685 : robots.txt 추가
- sitemap 추가
: 현재 sitemap 관련 라이브러리가 너무 오래된 라이브러리
특정 사이트를 통해 사이트맵 자동 생성해주는 방법도 있으나 우리 서비스의 모든 라우팅을 해당 서비스에 넣어야 함. -> 현재 로그인하면 무조건 dev로 넘어가는 버그로 인해 불가함
> [DAD-685] robots.txt 추가

- .github/workflows/dev_deploy.yml
- .github/workflows/release.yml
- DAD-706
- 배포 시 dev, prod secret 파일 분리
- WEB_SECRET을 WEB_DEV_SECRET, WEB_PROD_SECRET 으로 변경
> [DAD-706] refactor: 배포 시 dev, prod secret 파일 분리

- package-lock.json
- package.json
- src/components/atoms/CategoryItem/DescrptionElement.tsx
- src/components/atoms/CategoryItem/TitleElement.tsx
- src/components/molcules/ArticleScrapCard.tsx
- src/components/molcules/OtherScrapCard.tsx
- src/components/molcules/ProductScrapCard.tsx
- src/components/molcules/VideoScrapCard.tsx
- src/components/organisms/ScrapCard.tsx
- DAD-603 : description 더보기 처리
- DAD-605 : description html entity decode
- 상품, 기타, 비디오, 아티클 스크랩 타이틀과 설명 더보기 처리
- html entity decode 적용
[html entity decode에 사용한 라이브러리](https://www.npmjs.com/package/html-entities)
- 어떤 요소들이 무슨 이유로 html entity encoding되어있는지 불확실 -> 추후 decode 적용해야하는 요소 더 생길 수도 -> 원인 파악하고 해당하는 애들에만 적용해보기
> [DAD-598] 조회 개선

- package-lock.json
- package.json
- src/components/organisms/MemoCreateModal.tsx
- src/components/organisms/ScrapCreateModal.tsx
- src/components/organisms/ScrapDeleteModal.tsx
- src/components/organisms/ScrapEditModal.tsx
- DAD-711 : 동작 성공 스낵바 연결
- DAD-681 : 리액트 쿼리 설치
많은 이슈가 리액트 쿼리를 사용하여 해결하는 이슈여서 여기서 한 번 끊고 다시 진행하도록 하겠습니다.
> [DAD-711] 동작 성공 스낵바 연결

- index.html
- DAD-725
- 구글 사이트 인증 메타 태그 추가
> [DAD-725] feat: 구글 사이트 인증 메타 태그 추가

- public/robots.txt
- DAD-725
- robots.txt 변경
- 메인 페이지가 인식되지 않음.
> [DAD-725] fix: robots.txt 변경

- public/sitemap.xml
- DAD-725
- 현재 robots.txt 바탕으로 https://www.xml-sitemaps.com 사이트에서 생성한 sitemap.xml 파일 추가
- (현재는 메인 페이지만 검색되도록 설정함)
> [DAD-725] feat: sitemap.xml 파일 추가

- package-lock.json
- package.json
- src/App.tsx
- src/api/memo.ts
- src/api/scrap.ts
- src/components/atoms/CategoryItem/AuthorElement.tsx
- src/components/atoms/CategoryItem/AuthorImageElement.tsx
- src/components/atoms/CategoryItem/BlogNameElement.tsx
- src/components/atoms/CategoryItem/ChannelProfileElement.tsx
- src/components/atoms/CategoryItem/DescrptionElement.tsx
- src/components/atoms/CategoryItem/MemoAreaElement.tsx
- src/components/atoms/CategoryItem/PriceElement.tsx
- src/components/atoms/CategoryItem/PublishedDateElement.tsx
- src/components/atoms/CategoryItem/SiteNameElement.tsx
- src/components/atoms/CategoryItem/TitleElement.tsx
- src/components/atoms/CategoryItem/VideoInfosElement.tsx
- src/components/molcules/ArticleScrapCard.tsx
- src/components/molcules/OtherScrapCard.tsx
- src/components/molcules/ProductScrapCard.tsx
- src/components/molcules/VideoScrapCard.tsx
- src/components/organisms/ExistArticleScrapContainer.tsx
- src/components/organisms/ExistListScrapContainer.tsx
- src/components/organisms/ExistProductScrapContainer.tsx
- src/components/organisms/ExistVideoScrapContainer.tsx
- src/components/organisms/ScrapCreateModal.tsx
- src/components/templates/ArticleTemplate.tsx
- src/components/templates/ListTemplate.tsx
- src/components/templates/VideoTemplate.tsx
- DAD-681 : 리액트 쿼리 적용
- DAD-592 : 렌더링 개선
- 카테고리 페이지에서 메모 추가, 스크랩 추가 로직 리액트 쿼리 적용
- 전체, 기타 페이지 컴포넌트 일부 추상화
> [DAD-681] 리액트 쿼리 적용

- src/components/atoms/CategoryItem/VideoElement.tsx
- src/components/molcules/VideoScrapCard.tsx
- src/components/organisms/ExistArticleScrapContainer.tsx
- src/components/organisms/ExistListScrapContainer.tsx
- src/components/organisms/ExistProductScrapContainer.tsx
- src/components/organisms/ExistVideoScrapContainer.tsx
- DAD-722 
- 조회 가능 개수 30개로 변경
- 전체 스크랩 페이지에서 영상 iframe을 썸네일 이미지로 변경
- 비디오 prefetch 적용
> [DAD-722] 중간평가에 필요한 기능 구현

- src/api/scrap.ts
- src/components/organisms/ScrapDeleteModal.tsx
- DAD-745 : 스크랩 삭제 반영
- 스크랩 삭제 함수 분리
- 스크랩 삭제 로직을 리액트 쿼리로 변경
> [DAD-745] feat: 스크랩 삭제 바로 반영 적용

- src/components/molcules/ArticleScrapCard.tsx
- src/components/molcules/Navigation/MobileNavbar.tsx
- DAD-811
- 모바일 사이드바 유저 닉네임 제거
- 모바일 사이드바 스크롤 추가 및 가로 스크롤 제거
- 아티클 스크랩 카드 유저 이미지, 블로그 이름 추가
> [DAD-811] FE 9/7 팀원 피드백 반영

- src/assets/styles/themeMuiStyle.ts
- src/components/atoms/Icon.tsx
- src/components/molcules/ScrapListHeader.tsx
- src/components/molcules/SearchBar.tsx
- src/components/templates/ScrapTemplate.tsx
- DAD-815
- 검색바 추가
- 스크랩 개수 디자인 적용
- 스크랩 추가 버튼 변경
- 페이지 배경 및 높이 변경
> [DAD-815] 스크랩 페이지 공통부분 디자인 적용

- src/components/atoms/CategoryItem/Tooltip.tsx
- src/components/atoms/Navigation/NavigationMenuItem.tsx
- src/components/molcules/Navigation/Header.tsx
- src/components/molcules/Navigation/Navbar.tsx
- src/components/molcules/ScrapListHeader.tsx
- src/hooks/useCalculateDateDiff.ts
- src/index.css
- vite.config.ts
- DAD-816
- 모바일 클릭 영역에 생기는 파란 박스 제거
- auto focus 설정 변경
- 불필요한 배경 설정 변경
- backdrop filter 제거
- dayjs 날짜 차이 계산하는 로직 변경
: unix time을 date로 변경하여 해당 date로 날짜 차이를 계산하는 로직에서 unix time 자체로 계산할 수 있도록 변경됨.
> [DAD-816] 오류 수정

- src/components/molcules/Memo.tsx
- DAD-790
- 메모 자체 디자인 적용
- 메모 툴팁 기능 연결
- 툴팁 추상화
- desktop / mobile 메모 리스트 작업
> [DAD-790] style: 메모 컴포넌트 디자인 적용

- src/api/count.ts
- src/components/templates/MasonryListTemplate.tsx
- src/components/templates/MatchTemplateWithTypeAndCount.tsx
- src/components/templates/ScrapTemplate.tsx
- DAD-863
- masonry 배열 페이지 넓은 스크린에서는 width 줄어드는 오류 해결
- 스크랩 템플릿에서 가능한 템플릿끼리 충돌 해결
- 스크랩 템플릿에서 적절한 템플릿 매칭하는 컴포넌트 분리
- 스크랩 count 통신 로직 분리 및 리액트 쿼리 연결
> [DAD-863] 배포 피드백 반영

- package-lock.json
- package.json
- src/components/molcules/Board/ColumnContainer.tsx
- src/components/molcules/Board/TaskCard.tsx
- src/components/templates/BoardTemplate.tsx
> [DAD-867] 칸반 보드 클론 코딩

- src/api/scrap.ts
- DAD-870
스크랩 개수 유무 변경 시 페이지 오류 및 렌더링 안 되는 오류 해결
> [DAD-870] feat: 스크랩 개수 invalidate query 추가

- src/assets/styles/globalStorybook.tsx
확인해보니 폰트가 적용 안 되고 있었어서 수정했습니다~!
> [DAD-898] 스토리북 font 미적용 해결

- index.html
- package-lock.json
- package.json
- src/App.tsx
- src/components/molcules/CategoryItem/Memo/MemoCreateInput.tsx
- src/components/molcules/Navigation/Header.tsx
- src/components/molcules/Navigation/MobileNavbar.tsx
- src/components/molcules/Navigation/Navbar.tsx
- src/components/molcules/Navigation/ScrapNaviagtion.tsx
- src/components/templates/mainPage/Footer.tsx
- src/main.tsx
- src/pages/UserPage.tsx
- src/utility/RouteChangeTracker.ts
- 미구현 navigation 막기
- 이용약관 추가
- 유저 페이지 로그아웃 오류 해결
- 유저 페이지 이미지 변경하기 버튼 및 개인정보보호 제거
- 메모 추가 input error props 변경
- GA 붙이기
> [DAD-913] 배포 준비

- package-lock.json
- package.json
- src/App.tsx
- src/pages/OAuthLoginPage.tsx
- src/utility/Routing.tsx
- src/utility/amplitude.ts
> [DAD-915] amplitude 연결

- src/components/molcules/CategoryItem/CategoryScrapList/ColumnScrapListElement.tsx
- src/components/molcules/CategoryItem/Memo/MemoCreateInput.tsx
- src/components/molcules/Memo.tsx
- src/components/molcules/SearchBar.tsx
- src/components/organisms/ExistCategoryScrapContainer/CategoryInfo.tsx
- src/components/templates/ColumnListTemplate.tsx
> [DAD-907] fix: 검색 및 조회 로직 변경

- src/components/molcules/Memo.tsx
> [DAD-918] fix: 메모 영역 침범 오류 해결

- src/api/board.ts
- DAD-959
- 보드 업데이트 후 title 렌더링 미반영 수정
> [DAD-959] fix: 보드 업데이트 미반영 수정

- src/api/board.ts
- src/components/templates/BB.jsx
- src/hooks/useBoardContentAtom.ts
- src/pages/BoardInfoPage.tsx
- DAD-954 : update api 연결
- DAD-955 : 조회 api 연결
- update contents, get board contents api 연결
- 10초마다 update contents 설정 추가
- 보드 content 저장 로직을 atom에서 담당하도록 변경
> [DAD-945] 보드에 저장한 스크랩을 불러와서 볼 수 있다.

- src/hooks/useBoardContentAtom.ts
- DAD-976
- 편집 모드에서 열 추가하기 버튼 미동작 오류 해결
> [DAD-976] feat: 편집 모드에서 열 추가하기 버튼 미동작 오류 해결

- src/components/atoms/Modal/BoardShareModalElement.tsx
- src/hooks/useModal.tsx
- src/pages/BoardInfoPage.tsx
- src/stories/BoardShareModalElement.stories.ts
- DAD-1007
- 보드 공유 모달 컴포넌트 생성
- 링크 복사 기능 구현
- 토글 상태에 따라 버튼 disabled 처리 구현
> [DAD-1007] 공유 모달 UI 작업

- src/api/board.ts
- src/api/count.ts
- src/components/templates/BB.jsx
- src/pages/BoardInfoPage.tsx
- src/pages/ErrorPage.tsx
- DAD-1037
- DAD-1039
- 로그인 후 보드 페이지 진입 시 오류 해결
- Sentry 추가
- 보드 페이지 가로 스크롤 추가
> [DAD-1036] 보드 오류 해결

- src/pages/BoardInfoPage.tsx
> [DAD-1040] feat: 지웠던 공유 버튼 살리기

- src/pages/OpenBoardPage.tsx
> [DAD-1149] refactor: 불필요한 import 제거

- src/api/board.ts
- src/api/count.ts
- src/api/memo.ts
- src/api/scrap.ts
- src/api/trend.ts
- src/api/user.ts
- src/components/atoms/Board/CopyBoardButton.tsx
- src/components/atoms/Modal/BoardPublicModalElement.tsx
- src/components/atoms/Modal/BoardPublishModalElement.tsx
- src/components/atoms/Modal/ScrapPasteModalElement.tsx
- src/components/molcules/Navigation/Header.tsx
- src/components/molcules/Navigation/MobileNavbar.tsx
- src/components/molcules/Trending/TrendingCard.tsx
- src/components/organisms/EmptyTrendingContainer.tsx
- src/components/templates/BB.jsx
- src/components/templates/BoardListTemplate.tsx
- src/components/templates/ColumnListTemplate.tsx
- src/components/templates/MasonryListTemplate.tsx
- src/components/templates/TrashableItems.tsx
- src/hooks/useCalculateDateDiff.ts
- src/hooks/useModal.tsx
- src/pages/BoardInfoPage.tsx
- src/pages/OpenBoardPage.tsx
- src/pages/TrendingPage.tsx
- src/pages/UserPage.tsx
- src/state/boardAtom.ts
- src/types/IBoardAtom.ts
- src/utility/Routing.tsx
> [DAD-1140] 트렌딩 api 연결 및 게시 준비

- src/pages/TrendingPage.tsx
- 1201
- 무한스크롤 수정
- topic 영역 위치 반응형 적용
> [DAD-1201] fix: 무한스크롤 수정

- src/components/templates/BoardListTemplate.tsx
- src/pages/BoardInfoPage.tsx
- 1202
- 보드 페이지 모바일 뷰 적용
- 이미지 여백 제거
> [DAD-1202] 보드 목록에서 이미지 여백 제거

- src/components/atoms/Modal/BoardPublicModalElement.tsx
> [DAD-1203] feat: 보드 트렌딩 모달 닫기 버튼 추가

- src/components/molcules/Trending/TrendingCard.tsx
> [DAD-1204] fix: 트렌딩 사파리 간격 이상 수정

- src/api/board.ts
- src/api/trend.ts
- src/components/atoms/Board/CopyBoardButton.tsx
- src/components/molcules/Trending/TrendingCard.tsx
- DAD-1208
- 하트, 조회, 복사 로직에 트렌딩 재조회하는 로직 변경
> [DAD-1208] feat: 하트, 조회, 복사 동작에 트렌딩 재조회하는 로직 변경

- src/pages/UserPage.tsx
> [DAD-1222] feat: 이미지 변경 및 삭제 보이기

- src/pages/UserPage.tsx
> [DAD-1225] feat: 이미지 수정 가리기

- index.html
- manifest.json
- public/service-worker.js
- src/App.tsx
- vite.config.ts
- DAD-1226
- pwa 관련 설정 파일들 위치 변경
> [DAD-1226] fix: pwa 관련 설정 파일들 위치 변경

- vite.config.ts
> [DAD-1227] fix: vite 설정 변경

- index.html
- manifest.json
- service-worker.js
- src/App.tsx
- tsconfig.json
> [DAD-1228] fix: pwa 설정 변경

- vite.config.ts
> [DAD-1230] chore: vite 설정 변경

- service-worker.js
> [DAD-1232] feat: share 요청 코드 추가

- service-worker.js
- src/pages/ShareTarget.tsx
- src/utility/Routing.tsx
- DAD-1233
- share target api 수정
> [DAD-1233] share target api 수정

- service-worker.js
> [DAD-1234] fix: 서비스 워커 오류 해결

- service-worker.js
> [DAD-1235] feat: redirect url 수정

- service-worker.js
- shareTarget.html
- DAD-1236
- share target용 html 생성
> [DAD-1236] feat: share target용 html 생성

- service-worker.js
- DAD-1239
- offline 페이지 주소 수정
> [DAD-1239] feat: offline 페이지 주소 수정

- index.html
- package-lock.json
- service-worker.js
- DAD-1240
- index.html에서 share target 처리 시도
> [DAD-1240] feat: index.html에서 share target 처리 시도

- service-worker.js
- DAD-1245
- 스크랩 추가 url로 redirect
> [DAD-1245] feat: 스크랩 추가 url로 redirect

- service-worker.js
- DAD-1246
- data에서 가져오는 property 변경
> [DAD-1246] feat: data에서 가져오는 property 변경

- service-worker.js
> [DAD-1247] feat: async 추가

- public/manifest.webmanifest
- service-worker.js
> [DAD-1248] feat: text 읽기 시도

- service-worker.js
> [DAD-1249] feat: 303 추가

- service-worker.js
- src/pages/ShareTarget.tsx
> [DAD-1250] feat: 로그 찍기

- service-worker.js
> [DAD-1251] feat: 요청 url 조건문 제거

- index.html
- service-worker.js
- DAD-1252
- index.html에서 요청 처리
> [DAD-1252] feat: index.html에서 요청 처리

- public/manifest.webmanifest
- service-worker.js
- src/pages/ShareTarget.tsx
- DAD-1253
- manifest 파일 수정
- routing 주소 수정
> [DAD-1253] feat: manifest 수정

- index.html
> [DAD-1254] feat: index에서 요청 처리 시도

- src/components/atoms/ProfileImage.tsx
- src/components/molcules/Trending/TrendingCard.tsx
- src/pages/TrendingPage.tsx
> [DAD-1255] feat: 유저 이미지 오류 해결

- src/components/templates/mainPage/Footer.tsx
> [DAD-1256] feat: '주' 표현 제거

- index.html
- service-worker.js
> [DAD-1257] feat: 서비스워커 위치 경로 수정
